import './globals.css';
import './_normalize.scss';
import type { Metadata } from 'next';
import {raleWay} from '@/app/fonts';
import React from 'react'
import Header from "@/components/header/Header";
//import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={raleWay.className}>
      <Header/>
      <main>
        {children}
      </main>
      </body>
    </html>
  );
}
